package com.example.diplom

import android.Manifest
import android.content.Context
import android.net.Uri
import android.widget.Toast
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.animation.*
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.core.content.FileProvider
import androidx.navigation.NavController
import coil.compose.AsyncImage
import com.example.diplom.data.*
import com.example.diplom.ui.theme.InterFontFamily
import com.example.diplom.ui.theme.UmamiOrange
import com.example.diplom.ui.theme.UmamiGreen
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaTypeOrNull
import okhttp3.MultipartBody
import okhttp3.RequestBody.Companion.toRequestBody
import com.google.gson.Gson
import com.example.diplom.data.local.*
import java.io.File

data class StepData(
    var description: String = "",
    var imageUri: Uri? = null,
    var uploadedUrl: String? = null,
    var isUploading: Boolean = false
)

data class SelectedIngredientUi(
    val id: Int? = null,
    val name: String,
    val quantity: String = "",
    val unit: String = "",
    val note: String = ""
)

val UNIT_OPTIONS = listOf("г", "кг", "мл", "л", "шт", "ст. л.", "ч. л.", "стакан", "зубчик", "щепотка", "по вкусу")

val INGREDIENT_UNIT_SUGGESTIONS = mapOf(
    "Мука" to "г",
    "Сахар" to "г",
    "Молоко" to "мл",
    "Вода" to "мл",
    "Яйцо" to "шт",
    "Масло сливочное" to "г",
    "Масло растительное" to "мл",
    "Соль" to "щепотка",
    "Перец" to "по вкусу",
    "Лук" to "шт",
    "Чеснок" to "зубчик",
    "Картофель" to "г",
    "Мясо" to "г",
    "Курица" to "г",
    "Рис" to "г",
    "Макароны" to "г",
    "Сливки" to "мл",
    "Сыр" to "г"
)

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun AddRecipeScreen(navController: NavController, recipeId: String? = null, draftJson: String? = null) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()
    val service = ApiClient.recipeService

    val db = remember { UmamiDatabase.getDatabase(context) }
    val dao = db.dao()

    // Stepper state
    var currentStep by remember { mutableIntStateOf(0) }
    val stepTitles = listOf("Основа", "Ингредиенты", "Шаги", "Финиш")

    // Form state
    var title by remember { mutableStateOf("") }
    var description by remember { mutableStateOf("") }
    var cookingTime by remember { mutableStateOf("") }
    var portion by remember { mutableStateOf("") }
    var difficulty by remember { mutableStateOf("1") }
    var isPrivate by remember { mutableStateOf(false) }
    var isGenerated by remember { mutableStateOf(false) }
    var isParsed by remember { mutableStateOf(false) }

    // PFC
    var proteins by remember { mutableStateOf("") }
    var fats by remember { mutableStateOf("") }
    var carbohydrates by remember { mutableStateOf("") }
    var calorific by remember { mutableStateOf("") }

    // Image
    var mainImageUri by remember { mutableStateOf<Uri?>(null) }
    var mainImageUrl by remember { mutableStateOf<String?>(null) }
    var isMainImageUploading by remember { mutableStateOf(false) }

    // Steps
    val steps = remember { mutableStateListOf(StepData()) }

    // Metadata
    var categories by remember { mutableStateOf<List<Category>>(emptyList()) }
    var kitchens by remember { mutableStateOf<List<Category>>(emptyList()) }
    var cookingTypes by remember { mutableStateOf<List<Category>>(emptyList()) }
    var celebrations by remember { mutableStateOf<List<Category>>(emptyList()) }
    var ingredients by remember { mutableStateOf<List<Ingredient>>(emptyList()) }

    var selectedCategoryIds by remember { mutableStateOf<Set<String>>(emptySet()) }
    var selectedKitchenId by remember { mutableStateOf<String?>(null) }
    var selectedCookingId by remember { mutableStateOf<String?>(null) }
    var selectedCelebrationId by remember { mutableStateOf<String?>(null) }

    // Ingredient selection
    var ingredientSearch by remember { mutableStateOf("") }
    var selectedIngredients by remember { mutableStateOf<List<SelectedIngredientUi>>(emptyList()) }
    var showIngredientDialog by remember { mutableStateOf(false) }

    var isLoading by remember { mutableStateOf(false) }

    // Picker state
    var showImageSourceDialog by remember { mutableStateOf(false) }
    var imagePickTarget by remember { mutableStateOf("main") }
    var cameraImageUri by remember { mutableStateOf<Uri?>(null) }

    // Helper: Upload Image
    suspend fun uploadImage(uri: Uri, folder: String): String? {
        return withContext(Dispatchers.IO) {
            try {
                android.util.Log.d("AddRecipeScreen", "uploadImage start for uri: $uri, folder: $folder")
                val inputStream = context.contentResolver.openInputStream(uri) ?: return@withContext null
                val bytes = inputStream.readBytes()
                inputStream.close()
                val requestFile = bytes.toRequestBody("image/*".toMediaTypeOrNull())
                val imagePart = MultipartBody.Part.createFormData("image", "photo.jpg", requestFile)
                val folderPart = folder.toRequestBody("text/plain".toMediaTypeOrNull())
                val res = service.uploadImage(imagePart, folderPart)
                android.util.Log.d("AddRecipeScreen", "uploadImage success: ${res.url}")
                res.url
            } catch (e: Exception) {
                android.util.Log.e("AddRecipeScreen", "uploadImage failed for uri: $uri, folder: $folder", e)
                null
            }
        }
    }

    // Launchers
    val galleryLauncher = rememberLauncherForActivityResult(ActivityResultContracts.GetContent()) { uri ->
        uri?.let { 
            if (imagePickTarget == "main") {
                mainImageUri = it
                mainImageUrl = null // Clear old URL so it triggers upload
            } else {
                val idx = imagePickTarget.removePrefix("step_").toIntOrNull()
                if (idx != null && idx < steps.size) {
                    steps[idx] = steps[idx].copy(imageUri = it, uploadedUrl = null) // Clear old step URL
                }
            }
        }
    }
    val cameraLauncher = rememberLauncherForActivityResult(ActivityResultContracts.TakePicture()) { success ->
        if (success && cameraImageUri != null) {
            if (imagePickTarget == "main") {
                mainImageUri = cameraImageUri
                mainImageUrl = null // Clear old URL so it triggers upload
            } else {
                val idx = imagePickTarget.removePrefix("step_").toIntOrNull()
                if (idx != null && idx < steps.size) {
                    steps[idx] = steps[idx].copy(imageUri = cameraImageUri, uploadedUrl = null) // Clear old step URL
                }
            }
        }
    }
    val cameraPermissionLauncher = rememberLauncherForActivityResult(ActivityResultContracts.RequestPermission()) { granted ->
        if (granted) {
            val uri = createTempImageUri(context)
            cameraImageUri = uri
            cameraLauncher.launch(uri)
        }
    }

    // Load Initial Data
    LaunchedEffect(Unit) {
        try {
            categories = service.getCategories()
            kitchens = service.getKitchens()
            cookingTypes = service.getCookingTypes()
            celebrations = service.getCelebrations()
            ingredients = service.getIngredients()

            if (recipeId != null) {
                // ... (existing edit logic)
                isLoading = true
                val r = service.getRecipeById(recipeId)
                title = r.title ?: ""
                description = r.description ?: ""
                cookingTime = r.cookingTime?.toString() ?: ""
                portion = r.portion?.toString() ?: ""
                calorific = r.calorific?.toString() ?: ""
                proteins = r.proteins?.toString() ?: ""
                fats = r.fats?.toString() ?: ""
                carbohydrates = r.carbohydrates?.toString() ?: ""
                difficulty = r.difficulty ?: "1"
                isPrivate = r.isPrivate ?: false
                isGenerated = r.isGenerated ?: false
                isParsed = r.isParsed ?: false
                mainImageUrl = r.imageUrl
                selectedCategoryIds = r.categories?.map { it.id.toString() }?.toSet() ?: emptySet()
                selectedKitchenId = r.kitchen?.id?.toString()
                selectedCookingId = r.typeCooking?.id?.toString()
                selectedCelebrationId = r.celebration?.id?.toString()
                selectedIngredients = r.ingredients?.map { ing ->
                    val rawUnit = ing.pivot?.unit ?: ""
                    val cleanUnit = if (rawUnit.startsWith("__unit_override:")) rawUnit.substringAfter("__unit_override:") else rawUnit
                    val rawNote = ing.pivot?.note ?: ""
                    val cleanNote = if (rawNote.startsWith("__unit_override:")) "" else rawNote
                    SelectedIngredientUi(id = ing.id?.toIntOrNull(), name = ing.name ?: "", quantity = ing.pivot?.quantity ?: "", unit = cleanUnit, note = cleanNote)
                } ?: emptyList()
                steps.clear()
                r.steps?.sortedBy { it.stepNumber }?.forEach { steps.add(StepData(description = it.description, uploadedUrl = it.imageUrl)) }
                if (steps.isEmpty()) steps.add(StepData())
                isLoading = false
            } else if (draftJson != null || AiDraft.suggestion != null) {
                // ... (existing AI logic)
                val suggestion = if (draftJson != null) Gson().fromJson(draftJson, AiRecipeSuggestion::class.java) else null
                val draft = AiDraft.suggestion
                
                title = suggestion?.title ?: draft?.title ?: ""
                description = suggestion?.description ?: "Рецепт от ИИ-шефа"
                isGenerated = true
                isPrivate = true
                
                val sourceIngs = suggestion?.ingredients?.map { SelectedIngredientUi(name = it.name, quantity = it.quantity, unit = it.unit) }
                    ?: draft?.ingredients?.map { SelectedIngredientUi(name = it.name, quantity = it.quantity ?: "", unit = it.unit ?: "") }
                    ?: emptyList()
                selectedIngredients = sourceIngs
                
                steps.clear()
                (suggestion?.steps?.map { StepData(description = it.description) } 
                    ?: draft?.steps?.map { StepData(description = it.description) } 
                    ?: emptyList()).forEach { steps.add(it) }
                if (steps.isEmpty()) steps.add(StepData())
                AiDraft.suggestion = null
                // Try load from Room Draft
                val savedDraft = dao.getDraft()
                if (savedDraft != null && savedDraft.title.isNotBlank()) {
                    // We could show a dialog, but for now just auto-restore
                    title = savedDraft.title
                    description = savedDraft.description
                    val draftUrl = savedDraft.mainImageUrl
                    if (draftUrl != null && (draftUrl.startsWith("content://") || draftUrl.startsWith("file://"))) {
                        mainImageUrl = null
                        mainImageUri = Uri.parse(draftUrl)
                    } else {
                        mainImageUrl = draftUrl
                        mainImageUri = null
                    }
                    selectedIngredients = Gson().fromJson(savedDraft.ingredientsJson, Array<SelectedIngredientUi>::class.java).toList()
                    val savedSteps = Gson().fromJson(savedDraft.stepsJson, Array<StepData>::class.java).toList()
                    steps.clear()
                    steps.addAll(savedSteps.map { step ->
                        val stepUrl = step.uploadedUrl
                        if (stepUrl != null && (stepUrl.startsWith("content://") || stepUrl.startsWith("file://"))) {
                            step.copy(uploadedUrl = null, imageUri = Uri.parse(stepUrl))
                        } else {
                            step
                        }
                    })
                    Toast.makeText(context, "Черновик восстановлен", Toast.LENGTH_SHORT).show()
                }
            }
        } catch (e: Exception) { isLoading = false }
    }

    // Auto-Save Effect
    LaunchedEffect(
        title,
        description,
        selectedIngredients,
        steps.size,
        mainImageUrl,
        mainImageUri,
        steps.map { it.imageUri?.toString() ?: it.uploadedUrl }
    ) {
        if (recipeId == null && !isGenerated && title.isNotBlank()) {
            val stepsToSave = steps.map { step ->
                if (step.uploadedUrl == null && step.imageUri != null) {
                    step.copy(uploadedUrl = step.imageUri.toString())
                } else {
                    step
                }
            }
            val draft = LocalRecipeDraft(
                title = title,
                description = description,
                ingredientsJson = Gson().toJson(selectedIngredients),
                stepsJson = Gson().toJson(stepsToSave),
                mainImageUrl = mainImageUri?.toString() ?: mainImageUrl
            )
            dao.saveDraft(draft)
        }
    }

    Scaffold(
        topBar = {
            CenterAlignedTopAppBar(
                title = { Text(stepTitles[currentStep], fontFamily = InterFontFamily, fontWeight = FontWeight.Bold) },
                navigationIcon = { IconButton(onClick = { if (currentStep > 0) currentStep-- else navController.popBackStack() }) {
                    Icon(Icons.Default.ArrowBack, contentDescription = null)
                }},
                actions = {
                    Text("${currentStep + 1}/${stepTitles.size}", modifier = Modifier.padding(end = 16.dp), color = Color.Gray, fontSize = 14.sp)
                }
            )
        },
        bottomBar = {
            Surface(shadowElevation = 8.dp) {
                Row(modifier = Modifier.fillMaxWidth().padding(16.dp), horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                    if (currentStep > 0) {
                        OutlinedButton(onClick = { currentStep-- }, modifier = Modifier.weight(1f).height(50.dp), shape = RoundedCornerShape(12.dp)) {
                            Text("Назад", fontFamily = InterFontFamily)
                        }
                    }
                    Button(
                        onClick = {
                            if (currentStep < 3) {
                                // Validation before next step
                                if (currentStep == 0) {
                                    val timeVal = cookingTime.toIntOrNull()
                                    val portionVal = portion.toIntOrNull()
                                    if (title.isBlank()) {
                                        Toast.makeText(context, "Введите название", Toast.LENGTH_SHORT).show()
                                    } else if (description.isBlank()) {
                                        Toast.makeText(context, "Введите описание", Toast.LENGTH_SHORT).show()
                                    } else if (timeVal == null || timeVal < 1) {
                                        Toast.makeText(context, "Укажите корректное время приготовления (мин)", Toast.LENGTH_SHORT).show()
                                    } else if (portionVal == null || portionVal < 1) {
                                        Toast.makeText(context, "Укажите корректное число порций", Toast.LENGTH_SHORT).show()
                                    } else {
                                        currentStep++
                                    }
                                } else if (currentStep == 1) {
                                    if (selectedIngredients.isEmpty()) {
                                        Toast.makeText(context, "Рецепт должен содержать хотя бы один ингредиент", Toast.LENGTH_SHORT).show()
                                    } else {
                                        currentStep++
                                    }
                                } else if (currentStep == 2) {
                                    if (steps.isEmpty() || steps.any { it.description.isBlank() }) {
                                        Toast.makeText(context, "Опишите все шаги приготовления", Toast.LENGTH_SHORT).show()
                                    } else {
                                        currentStep++
                                    }
                                } else {
                                    currentStep++
                                }
                            } else {
                                // Final Publish
                                scope.launch {
                                    isLoading = true
                                    try {
                                        // 1. Upload images if needed
                                        var mainUrlToUse = mainImageUrl
                                        if (mainUrlToUse != null && (mainUrlToUse.startsWith("content://") || mainUrlToUse.startsWith("file://"))) {
                                            mainUrlToUse = null
                                        }
                                        android.util.Log.d("AddRecipeScreen", "PUBLISH START: mainImageUri=$mainImageUri, mainImageUrl=$mainImageUrl, mainUrlToUse=$mainUrlToUse")
                                        if (mainImageUri != null && mainUrlToUse == null) {
                                            isMainImageUploading = true
                                            android.util.Log.d("AddRecipeScreen", "PUBLISH: Uploading main image $mainImageUri")
                                            mainUrlToUse = uploadImage(mainImageUri!!, "recipes")
                                            mainImageUrl = mainUrlToUse
                                            android.util.Log.d("AddRecipeScreen", "PUBLISH: Uploaded main image URL=$mainUrlToUse")
                                            isMainImageUploading = false
                                        }
                                        val stepsWithUploadedUrls = steps.mapIndexed { index, step ->
                                            var stepUrl = step.uploadedUrl
                                            if (stepUrl != null && (stepUrl.startsWith("content://") || stepUrl.startsWith("file://"))) {
                                                stepUrl = null
                                            }
                                            if (step.imageUri != null && stepUrl == null) {
                                                steps[index] = step.copy(isUploading = true)
                                                val uploaded = uploadImage(step.imageUri!!, "steps")
                                                val updatedStep = step.copy(uploadedUrl = uploaded, isUploading = false)
                                                steps[index] = updatedStep
                                                updatedStep
                                            } else {
                                                step
                                            }
                                        }

                                        val request = CreateRecipeRequest(
                                            title = title,
                                            description = description,
                                            difficulty = difficulty,
                                            imageUrl = mainUrlToUse,
                                            cookingTime = cookingTime.replace(",", ".").toIntOrNull() ?: 0,
                                            portion = portion.replace(",", ".").toIntOrNull() ?: 1,
                                            calorific = calorific.replace(",", ".").toIntOrNull(),
                                            proteins = proteins.replace(",", ".").toFloatOrNull(),
                                            fats = fats.replace(",", ".").toFloatOrNull(),
                                            carbohydrates = carbohydrates.replace(",", ".").toFloatOrNull(),
                                            isPrivate = if (isGenerated || isParsed) true else isPrivate,
                                            isGenerated = isGenerated,
                                            isParsed = isParsed,
                                            kitchenId = selectedKitchenId?.toIntOrNull(),
                                            celebrationId = selectedCelebrationId?.toIntOrNull(),
                                            cookingId = selectedCookingId?.toIntOrNull(),
                                            ingredients = selectedIngredients.map { IngredientInput(id = it.id, name = if (it.id == null) it.name else null, quantity = it.quantity, unit = it.unit, note = it.note) },
                                            steps = stepsWithUploadedUrls.mapIndexed { idx, s -> StepInput(stepNumber = idx + 1, description = s.description, imageUrl = s.uploadedUrl) },
                                            categories = selectedCategoryIds.mapNotNull { it.toIntOrNull() }
                                        )

                                        if (recipeId == null) {
                                            service.createRecipe(request)
                                        } else {
                                            // Send everything in update too
                                            service.updateRecipe(recipeId, mapOf<String, Any?>(
                                                "title" to request.title,
                                                "description" to request.description,
                                                "difficulty" to request.difficulty,
                                                "image_url" to request.imageUrl,
                                                "cooking_time" to request.cookingTime,
                                                "portion" to request.portion,
                                                "calorific" to request.calorific,
                                                "proteins" to request.proteins,
                                                "fats" to request.fats,
                                                "carbohydrates" to request.carbohydrates,
                                                "is_private" to request.isPrivate,
                                                "is_generated" to request.isGenerated,
                                                "is_parsed" to request.isParsed,
                                                "kitchen_id" to request.kitchenId,
                                                "celebration_id" to request.celebrationId,
                                                "cooking_id" to request.cookingId,
                                                "ingredients" to request.ingredients.map { 
                                                    mapOf(
                                                        "id" to it.id,
                                                        "name" to it.name,
                                                        "quantity" to it.quantity,
                                                        "unit" to it.unit,
                                                        "note" to it.note
                                                    ).filterValues { v -> v != null }
                                                },
                                                "steps" to request.steps.map {
                                                    mapOf(
                                                        "step_number" to it.stepNumber,
                                                        "description" to it.description,
                                                        "image_url" to it.imageUrl
                                                    ).filterValues { v -> v != null }
                                                },
                                                "categories" to request.categories
                                            ).filterValues { it != null } as Map<String, Any>)
                                        }

                                        dao.deleteDraft() // Clear draft on success
                                        Toast.makeText(context, "Готово!", Toast.LENGTH_SHORT).show()
                                        navController.popBackStack()
                                    } catch (e: Exception) {
                                        android.util.Log.e("AddRecipeScreen", "Failed to save recipe", e)
                                        val errorMsg = if (e is retrofit2.HttpException) {
                                            try {
                                                val json = e.response()?.errorBody()?.string()
                                                val map = Gson().fromJson(json, Map::class.java)
                                                map["message"]?.toString() ?: "Ошибка сохранения"
                                            } catch (_: Exception) {
                                                "Ошибка сохранения"
                                            }
                                        } else {
                                            "Ошибка сохранения"
                                        }
                                        Toast.makeText(context, errorMsg, Toast.LENGTH_LONG).show()
                                    } finally { isLoading = false }
                                }
                            }
                        },
                        modifier = Modifier.weight(1f).height(50.dp),
                        shape = RoundedCornerShape(12.dp),
                        colors = ButtonDefaults.buttonColors(containerColor = UmamiOrange),
                        enabled = !isLoading
                    ) {
                        if (isLoading) CircularProgressIndicator(color = Color.White, modifier = Modifier.size(20.dp), strokeWidth = 2.dp)
                        else Text(if (currentStep == 3) "Опубликовать" else "Далее", fontFamily = InterFontFamily, fontWeight = FontWeight.Bold)
                    }
                }
            }
        }
    ) { padding ->
        Column(modifier = Modifier.padding(padding).fillMaxSize()) {
            // Step Indicator dots
            Row(modifier = Modifier.fillMaxWidth().padding(vertical = 8.dp), horizontalArrangement = Arrangement.Center) {
                repeat(stepTitles.size) { i ->
                    Box(modifier = Modifier.padding(4.dp).size(8.dp).clip(CircleShape).background(if (i == currentStep) UmamiOrange else Color.LightGray))
                }
            }

            Box(modifier = Modifier.fillMaxSize()) {
                AnimatedContent(targetState = currentStep, transitionSpec = { fadeIn() togetherWith fadeOut() }, label = "FormStep") { step ->
                    when (step) {
                        0 -> BaseInfoStep(title, {title=it}, description, {description=it}, cookingTime, {cookingTime=it}, portion, {portion=it}, difficulty, {difficulty=it}, mainImageUri, mainImageUrl) {
                            imagePickTarget = "main"; showImageSourceDialog = true
                        }
                        1 -> IngredientsStep(selectedIngredients, {selectedIngredients=it}) { showIngredientDialog = true }
                        2 -> StepsStep(steps, { target -> imagePickTarget = target; showImageSourceDialog = true })
                        3 -> FinalStep(isPrivate, {isPrivate=it}, isGenerated, isParsed, selectedCategoryIds, {selectedCategoryIds=it}, categories, selectedKitchenId, {selectedKitchenId=it}, kitchens, selectedCookingId, {selectedCookingId=it}, cookingTypes, selectedCelebrationId, {selectedCelebrationId=it}, celebrations, proteins, {proteins=it}, fats, {fats=it}, carbohydrates, {carbohydrates=it}, calorific, {calorific=it})
                    }
                }
            }
        }
    }

    if (showImageSourceDialog) {
        ImageSourceDialog({ showImageSourceDialog = false }, { galleryLauncher.launch("image/*") }, { cameraPermissionLauncher.launch(Manifest.permission.CAMERA) })
    }

    if (showIngredientDialog) {
        IngredientSelectionDialog(ingredients, selectedIngredients, { selectedIngredients = it }, { showIngredientDialog = false })
    }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun BaseInfoStep(title: String, onTitle: (String) -> Unit, desc: String, onDesc: (String) -> Unit, time: String, onTime: (String) -> Unit, portion: String, onPortion: (String) -> Unit, difficulty: String, onDifficulty: (String) -> Unit, imageUri: Uri?, imageUrl: String?, onPickImage: () -> Unit) {
    LazyColumn(modifier = Modifier.fillMaxSize(), contentPadding = PaddingValues(20.dp), verticalArrangement = Arrangement.spacedBy(16.dp)) {
        item {
            Box(modifier = Modifier.fillMaxWidth().height(200.dp).clip(RoundedCornerShape(16.dp)).background(Color(0xFFF5F5F5)).clickable { onPickImage() }, contentAlignment = Alignment.Center) {
                if (imageUri != null) {
                    AsyncImage(model = imageUri, contentDescription = null, modifier = Modifier.fillMaxSize(), contentScale = ContentScale.Crop)
                } else if (imageUrl != null) {
                    AsyncImage(model = normalizeImageUrl(imageUrl), contentDescription = null, modifier = Modifier.fillMaxSize(), contentScale = ContentScale.Crop)
                } else {
                    Column(horizontalAlignment = Alignment.CenterHorizontally) {
                        Icon(Icons.Default.AddPhotoAlternate, contentDescription = null, modifier = Modifier.size(48.dp), tint = Color.Gray)
                        Text("Добавить главное фото", color = Color.Gray, fontFamily = InterFontFamily)
                    }
                }
            }
        }
        item { CustomTextField("Название", title, onTitle, placeholder = "Напр. Борщ по-домашнему") }
        item { CustomTextField("Описание", desc, onDesc, singleLine = false, minLines = 3) }
        item {
            Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                Box(modifier = Modifier.weight(1f)) { CustomTextField("Время (мин)", time, onTime, keyboardType = KeyboardType.Number) }
                Box(modifier = Modifier.weight(1f)) { CustomTextField("Порции", portion, onPortion, keyboardType = KeyboardType.Number) }
            }
        }
        item {
            Text("Сложность (1-5)", fontFamily = InterFontFamily, fontWeight = FontWeight.Bold, fontSize = 14.sp)
            Slider(value = difficulty.toFloatOrNull() ?: 1f, onValueChange = { onDifficulty(it.toInt().toString()) }, valueRange = 1f..5f, steps = 3, colors = SliderDefaults.colors(thumbColor = UmamiOrange, activeTrackColor = UmamiOrange))
        }
    }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun IngredientsStep(selected: List<SelectedIngredientUi>, onUpdate: (List<SelectedIngredientUi>) -> Unit, onOpenDialog: () -> Unit) {
    LazyColumn(modifier = Modifier.fillMaxSize(), contentPadding = PaddingValues(20.dp)) {
        item {
            Button(onClick = onOpenDialog, modifier = Modifier.fillMaxWidth(), shape = RoundedCornerShape(12.dp), colors = ButtonDefaults.buttonColors(containerColor = UmamiGreen)) {
                Icon(Icons.Default.Add, contentDescription = null)
                Text("Добавить ингредиент", fontFamily = InterFontFamily)
            }
            Spacer(modifier = Modifier.height(16.dp))
        }
        itemsIndexed(selected) { index, ing ->
            Card(modifier = Modifier.fillMaxWidth().padding(vertical = 4.dp), shape = RoundedCornerShape(12.dp), colors = CardDefaults.cardColors(containerColor = Color(0xFFFAFAFA))) {
                Column(modifier = Modifier.padding(12.dp)) {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Text(ing.name, fontWeight = FontWeight.Bold, modifier = Modifier.weight(1f), fontFamily = InterFontFamily)
                        IconButton(onClick = { onUpdate(selected.toMutableList().apply { removeAt(index) }) }) {
                            Icon(Icons.Default.Delete, contentDescription = null, tint = Color.LightGray, modifier = Modifier.size(20.dp))
                        }
                    }
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        Box(modifier = Modifier.weight(1f)) {
                            OutlinedTextField(
                                value = ing.quantity,
                                onValueChange = { q -> 
                                    // Allow only digits and one dot/comma
                                    if (q.isEmpty() || q.matches(Regex("""^\d*[.,]?\d*$"""))) {
                                        onUpdate(selected.toMutableList().apply { this[index] = ing.copy(quantity = q.replace(",", ".")) })
                                    }
                                },
                                placeholder = {Text("Кол-во", fontSize = 12.sp)},
                                textStyle = LocalTextStyle.current.copy(fontSize = 14.sp),
                                modifier = Modifier.height(52.dp),
                                shape = RoundedCornerShape(8.dp),
                                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number)
                            )
                        }
                        Box(modifier = Modifier.weight(1f)) {
                           var expanded by remember { mutableStateOf(false) }
                           ExposedDropdownMenuBox(expanded = expanded, onExpandedChange = { expanded = it }) {
                               OutlinedTextField(value = ing.unit, onValueChange = {}, readOnly = true, modifier = Modifier.menuAnchor().height(52.dp), textStyle = LocalTextStyle.current.copy(fontSize = 14.sp), shape = RoundedCornerShape(8.dp), trailingIcon = { ExposedDropdownMenuDefaults.TrailingIcon(expanded = expanded) })
                               ExposedDropdownMenu(expanded = expanded, onDismissRequest = { expanded = false }) {
                                   UNIT_OPTIONS.forEach { option ->
                                       DropdownMenuItem(text = { Text(option) }, onClick = { onUpdate(selected.toMutableList().apply { this[index] = ing.copy(unit = option) }); expanded = false })
                                   }
                               }
                           }
                        }
                    }
                }
            }
        }
    }
}

@Composable
fun StepsStep(steps: List<StepData>, onPickImage: (String) -> Unit) {
    val context = LocalContext.current
    LazyColumn(modifier = Modifier.fillMaxSize(), contentPadding = PaddingValues(20.dp), verticalArrangement = Arrangement.spacedBy(16.dp)) {
        itemsIndexed(steps) { index, step ->
            Card(modifier = Modifier.fillMaxWidth(), shape = RoundedCornerShape(16.dp), colors = CardDefaults.cardColors(containerColor = Color.White), border = BorderStroke(1.dp, Color(0xFFF0F0F0))) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Text("Шаг ${index + 1}", fontWeight = FontWeight.Bold, color = UmamiOrange, fontFamily = InterFontFamily)
                        Spacer(modifier = Modifier.weight(1f))
                        if (steps.size > 1) {
                            IconButton(onClick = { (steps as MutableList).removeAt(index) }) {
                                Icon(Icons.Default.RemoveCircleOutline, contentDescription = null, tint = Color.LightGray)
                            }
                        }
                    }
                    Row(modifier = Modifier.fillMaxWidth().height(100.dp), horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                        Box(modifier = Modifier.size(100.dp).clip(RoundedCornerShape(12.dp)).background(Color(0xFFF9F9F9)).clickable { onPickImage("step_$index") }, contentAlignment = Alignment.Center) {
                            if (step.imageUri != null) AsyncImage(model = step.imageUri, contentDescription = null, modifier = Modifier.fillMaxSize(), contentScale = ContentScale.Crop)
                            else if (step.uploadedUrl != null) AsyncImage(model = normalizeImageUrl(step.uploadedUrl), contentDescription = null, modifier = Modifier.fillMaxSize(), contentScale = ContentScale.Crop)
                            else Icon(Icons.Default.AddAPhoto, contentDescription = null, tint = Color.LightGray)
                            
                            if (step.isUploading) CircularProgressIndicator(modifier = Modifier.size(32.dp), color = UmamiOrange)
                        }
                        OutlinedTextField(value = step.description, onValueChange = { d -> (steps as MutableList)[index] = step.copy(description = d) }, modifier = Modifier.weight(1f).fillMaxHeight(), placeholder = { Text("Опишите процесс...", fontSize = 13.sp) }, shape = RoundedCornerShape(12.dp))
                    }
                }
            }
        }
        item {
            TextButton(onClick = { (steps as MutableList).add(StepData()) }, modifier = Modifier.fillMaxWidth()) {
                Icon(Icons.Default.Add, contentDescription = null)
                Text("Добавить шаг")
            }
        }
    }
}

@OptIn(ExperimentalMaterial3Api::class, ExperimentalLayoutApi::class)
@Composable
fun FinalStep(isPrivate: Boolean, onPrivate: (Boolean) -> Unit, isGenerated: Boolean, isParsed: Boolean, selectedCats: Set<String>, onUpdateCats: (Set<String>) -> Unit, categories: List<Category>, selectedKitchen: String?, onKitchen: (String?) -> Unit, kitchens: List<Category>, selectedCooking: String?, onCooking: (String?) -> Unit, cookingTypes: List<Category>, selectedCelebration: String?, onCelebration: (String?) -> Unit, celebrations: List<Category>, p: String, onP: (String) -> Unit, f: String, onF: (String) -> Unit, c: String, onC: (String) -> Unit, cal: String, onCal: (String) -> Unit) {
    LazyColumn(modifier = Modifier.fillMaxSize(), contentPadding = PaddingValues(20.dp), verticalArrangement = Arrangement.spacedBy(16.dp)) {
        item {
            Text("Нутриенты (БЖУ)", fontWeight = FontWeight.Bold, fontFamily = InterFontFamily)
            Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                Box(modifier = Modifier.weight(1f)) { CustomTextField("Белки", p, onP, KeyboardType.Number) }
                Box(modifier = Modifier.weight(1f)) { CustomTextField("Жиры", f, onF, KeyboardType.Number) }
                Box(modifier = Modifier.weight(1f)) { CustomTextField("Углеводы", c, onC, KeyboardType.Number) }
            }
            CustomTextField("Калории", cal, onCal, KeyboardType.Number)
            Text("Если оставить пустым, ИИ рассчитает автоматически на основе ингредиентов", fontSize = 11.sp, color = Color.Gray, fontFamily = InterFontFamily)
        }
        item {
            Text("Категории", fontWeight = FontWeight.Bold, fontFamily = InterFontFamily)
            FlowRow(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                categories.forEach { cat ->
                    val isSelected = selectedCats.contains(cat.id.toString())
                    FilterChip(selected = isSelected, onClick = { onUpdateCats(if(isSelected) selectedCats - cat.id.toString() else selectedCats + cat.id.toString()) }, label = {Text(cat.name)})
                }
            }
        }
        item {
            DropdownSelector("Кухня мира", kitchens, selectedKitchen, onKitchen)
            Spacer(modifier = Modifier.height(12.dp))
            DropdownSelector("Тип готовки", cookingTypes, selectedCooking, onCooking)
            Spacer(modifier = Modifier.height(12.dp))
            DropdownSelector("Праздник", celebrations, selectedCelebration, onCelebration)
        }
        item {
            Row(verticalAlignment = Alignment.CenterVertically) {
                val isLocked = isGenerated || isParsed
                Text("Приватный рецепт", modifier = Modifier.weight(1f), fontFamily = InterFontFamily)
                Switch(checked = isPrivate, onCheckedChange = if (isLocked) null else onPrivate, colors = SwitchDefaults.colors(checkedThumbColor = UmamiOrange, checkedTrackColor = UmamiOrange.copy(alpha = 0.5f)))
            }
            if (isGenerated) Text("Сгенерированные ИИ рецепты всегда приватны", color = Color.Gray, fontSize = 12.sp)
            if (isParsed) Text("Импортированные рецепты всегда приватны", color = Color.Gray, fontSize = 12.sp)
        }
    }
}

@Composable
fun CustomTextField(label: String, value: String, onValueChange: (String) -> Unit, keyboardType: KeyboardType = KeyboardType.Text, singleLine: Boolean = true, minLines: Int = 1, placeholder: String = "") {
    Column {
        Text(label, fontWeight = FontWeight.Bold, fontSize = 14.sp, fontFamily = InterFontFamily, modifier = Modifier.padding(bottom = 4.dp))
        OutlinedTextField(value = value, onValueChange = onValueChange, modifier = Modifier.fillMaxWidth(), shape = RoundedCornerShape(12.dp), keyboardOptions = KeyboardOptions(keyboardType = keyboardType), singleLine = singleLine, minLines = minLines, placeholder = { if(placeholder.isNotBlank()) Text(placeholder, fontSize = 14.sp) }, colors = OutlinedTextFieldDefaults.colors(unfocusedBorderColor = Color(0xFFE5E5E5), focusedBorderColor = UmamiOrange))
    }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun DropdownSelector(label: String, items: List<Category>, selectedId: String?, onSelected: (String?) -> Unit) {
    var expanded by remember { mutableStateOf(false) }
    val selectedItem = items.find { it.id.toString() == selectedId }
    
    ExposedDropdownMenuBox(expanded = expanded, onExpandedChange = { expanded = it }) {
        OutlinedTextField(value = selectedItem?.name ?: "Не выбрано", onValueChange = {}, readOnly = true, label = {Text(label)}, modifier = Modifier.fillMaxWidth().menuAnchor(), shape = RoundedCornerShape(12.dp), trailingIcon = { ExposedDropdownMenuDefaults.TrailingIcon(expanded = expanded) })
        ExposedDropdownMenu(expanded = expanded, onDismissRequest = { expanded = false }) {
            DropdownMenuItem(text = {Text("Не выбрано")}, onClick = { onSelected(null); expanded = false })
            items.forEach { item ->
                DropdownMenuItem(text = {Text(item.name)}, onClick = { onSelected(item.id.toString()); expanded = false })
            }
        }
    }
}

@Composable
fun ImageSourceDialog(onDismiss: () -> Unit, onGallery: () -> Unit, onCamera: () -> Unit) {
    AlertDialog(onDismissRequest = onDismiss, title = { Text("Фотография") }, text = {
        Column {
            TextButton(onClick = onGallery, modifier = Modifier.fillMaxWidth()) { Icon(Icons.Default.Image, null); Spacer(Modifier.width(12.dp)); Text("Галерея", color = Color.Black) }
            TextButton(onClick = onCamera, modifier = Modifier.fillMaxWidth()) { Icon(Icons.Default.CameraAlt, null); Spacer(Modifier.width(12.dp)); Text("Камера", color = Color.Black) }
        }
    }, confirmButton = {})
}

@Composable
fun IngredientSelectionDialog(all: List<Ingredient>, selected: List<SelectedIngredientUi>, onUpdate: (List<SelectedIngredientUi>) -> Unit, onDismiss: () -> Unit) {
    var search by remember { mutableStateOf("") }
    AlertDialog(onDismissRequest = onDismiss, title = {Text("Ингредиенты")}, text = {
        Column {
            OutlinedTextField(value = search, onValueChange = {search=it}, placeholder = {Text("Поиск...")}, modifier = Modifier.fillMaxWidth(), shape = RoundedCornerShape(12.dp))
            val filtered = all.filter { it.name.contains(search, true) }.take(20)
            LazyColumn(modifier = Modifier.heightIn(max = 300.dp)) {
                if (search.isNotBlank() && filtered.none { it.name.equals(search, true) }) {
                    item { TextButton(onClick = { onUpdate(selected + SelectedIngredientUi(name = search.trim())); search = "" }) { Icon(Icons.Default.Add, null); Text("Добавить \"$search\"") } }
                }
                items(filtered) { ing ->
                    val isAdded = selected.any { it.id == ing.id.toIntOrNull() }
                    Row(modifier = Modifier.fillMaxWidth().clickable { 
                        if(!isAdded) {
                            val suggestedUnit = INGREDIENT_UNIT_SUGGESTIONS.entries.find { it.key.equals(ing.name, ignoreCase = true) }?.value ?: ""
                            onUpdate(selected + SelectedIngredientUi(id = ing.id.toIntOrNull(), name = ing.name, unit = suggestedUnit))
                        }
                    }.padding(8.dp), verticalAlignment = Alignment.CenterVertically) {
                        Text(ing.name, modifier = Modifier.weight(1f))
                        if(isAdded) Icon(Icons.Default.Check, null, tint = UmamiOrange)
                    }
                }
            }
        }
    }, confirmButton = { TextButton(onClick = onDismiss) {Text("Готово", color = UmamiOrange)} })
}

private fun createTempImageUri(context: Context): Uri {
    val imagesDir = File(context.cacheDir, "images")
    if (!imagesDir.exists()) {
        imagesDir.mkdirs()
    }
    val file = File.createTempFile("recipe_photo_", ".jpg", imagesDir)
    return FileProvider.getUriForFile(context, "${context.packageName}.provider", file)
}
